A:
  - record: vps01
    value: 85.215.184.231
  - record: vps03
    value: 51.75.203.179
  - record: vps06
    value : 5.135.152.108

CNAME:
  - record: '@'
    value: vps01.manitra.net
  - record: www
    value: vps01.manitra.net
  - record: merge
    value: vps01.manitra.net